// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type SearchResultBase interface {
	IsSearchResultBase()
}

type Cms struct {
	ID          string    `json:"id"`
	ContentID   string    `json:"contentID"`
	ContentType string    `json:"contentType"`
	MetaData    *MetaData `json:"meta_data"`
}

func (Cms) IsSearchResultBase() {}

type Content struct {
	ID     string             `json:"id"`
	Result []SearchResultBase `json:"result"`
}

func (Content) IsEntity() {}

type MetaData struct {
	URL   string `json:"url"`
	Title string `json:"title"`
}

type ScoreCard struct {
	ID            string     `json:"id"`
	ContentID     string     `json:"contentID"`
	ContentType   string     `json:"contentType"`
	ScoreCardData *ScoreData `json:"score_card_data"`
}

func (ScoreCard) IsSearchResultBase() {}

type ScoreData struct {
	Title string  `json:"title"`
	Team  []*Team `json:"team"`
}

type Team struct {
	Name  string `json:"name"`
	Score int    `json:"score"`
}
