// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Content struct {
	ID          string `json:"id"`
	ContentType string `json:"ContentType"`
}

func (Content) IsEntity() {}
